---
# Common variables for ALL hosts
ansible_user: mike
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

k3s_version: "v1.28.0+k3s1"
k3s_master_ip: "10.17.3.201"

k3s_install_script: https://get.k3s.io